### PR TITLE
Remove browserify

### PR DESCRIPTION
**Pull request by mariusglauer**
This is needed for meteor 1.3 support as said in #30.

### CODE REVIEW

**Comment by v3rron** [comment]
@arunoda can you please merge this PR ? Meteor 1.3 is officially out today

**Comment by driventv** [comment]
Yea, I really need this package to work.  I'm not sure of any other way to include dochead href links in mantra.

**Comment by rafa-munoz** [comment]
:+1: It's breaking compatibility with 1.3. @arunoda please merge! :)

**Comment by arunoda** [comment]
Guys, merged #32 instead of this.
Thanks for this PR.

**Pull request closed without merging**
