### PR TITLE
Rich snippets

### PR DESCRIPTION
**Pull request by PEM--**
- Remove React in favor of Ecmascript
- Add `addLdJsonScript` method for Rich Snippets support

### CODE REVIEW

**Comment by arunoda** [comment]
Awesome.

**Comment by arunoda** [comment]
Released as: `v2.2.0`

**Comment by PEM--** [comment]
Thanks for the merge and package update. And another thank for your incredible products. I'm pushing all my customers on them. I hope that sooner or later some of them will want to get deeper into them :wink:

**Comment by arunoda** [comment]
Awesome :)

**Pull request merged**
